### ISSUE TITLE
questions about AL and DAL

### ISSUE THREAD

**Issue by Onoratofra** [facebookresearch/SimulEval#11]
Hi! I was looking at the code SimulEval/simuleval/metrics/latency.py in order to understand how you implemented the metrics for latency that you defined in your paper about SimulEval.
I have a few questions I'd like to ask: can you confirm that in the code the calculation of AL considers the reference length rather than the prediction length as you described in the paper in equation 8?
If so, why did you not apply the same correction also to the calculation of DAL (both in the code and in the paper)? 

Thank you very much in advance!

**Comment by xutaima** [comment]
Hi @Onoratofra, thanks for your question.

1. Yes the AL considers the reference length as we described in the paper. We find that when the prediction length is significantly shorter than the reference length, the AL is not accurate anymore because the oracle system would have very bad delays in this case.

2. As to the DAL, potentially it has the similar issue when the prediction is way shorter than reference. However we didn't explore into this direction since DAL is less intuitive compared with AL. I will add an option to enable DAL calculation using reference length as well.

**Comment by Onoratofra** [comment]
Dear @xutaima thank you very very much for the answer!
